// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKbl-txVkQgc1QPkqskYeBGzprV4ENJto',
    appId: '1:467604215279:web:3727806ce9e796c42e921a',
    messagingSenderId: '467604215279',
    projectId: 'profanity-9a335',
    authDomain: 'profanity-9a335.firebaseapp.com',
    storageBucket: 'profanity-9a335.appspot.com',
    measurementId: 'G-DQHW3BWQZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH7AOdjGdoUIhqoxxSsp0czcFeEHRIBz4',
    appId: '1:467604215279:android:0df9157cf43bea522e921a',
    messagingSenderId: '467604215279',
    projectId: 'profanity-9a335',
    storageBucket: 'profanity-9a335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgmG4Bh923C_xn9zFCx3vd-geSRthGH38',
    appId: '1:467604215279:ios:db6d56aaf127379f2e921a',
    messagingSenderId: '467604215279',
    projectId: 'profanity-9a335',
    storageBucket: 'profanity-9a335.appspot.com',
    iosClientId: '467604215279-rlce0at3g99avpltubr4802l3nh7hm0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.profanity',
  );
}
